project:
  type: website
  output-dir: docs

website:
  title: "Jacob K. McPherson"
  description: "A Personal Website"
  favicon: logo.ico
  navbar:
    logo: logo.png
    pinned: true
    background: primary
    search: true
    left: 
      - href: index.qmd
        text: ""
      - href: about.qmd
        text: ""
      - href: blog/index.qmd
        text: ""
      - href: research/index.qmd
        text: ""
      - href: gallery/index.qmd
        text: ""

    right:
      - icon: vector-pen
        href: https://author.link/JacobKMcPherson/
        aria-label: Author.Link
      - icon: book
        href: https://scholar.google.com/citations?user=MsZPCoIAAAAJ&hl=en
        aria-label: Google Scholar
      - icon: calendar-date
        href: https://calendar.app.google/U3ZhDHVpvkYRY2aj7
        aria-label: Calendar
      - icon: envelope
        href: mailto:jacobmcpherson@utexas.edu;jkmcpherson@uh.edu;jacob@jacobkmcpherson.com
        aria-label: Email
      - icon: people
        href: https://mcphersongroup.github.io/
        aria-label: Research Group
      - icon: building
        href: https://jacobkmcpherson.com
        aria-label: Business
      - icon: linkedin
        href: https://linkedin.com/in/jacobkmcpherson/
        aria-label: LinkedIn
      - icon: github
        href: https://github.com/JacobKMcPherson/
        aria-label: GitHub
      - icon: bluesky
        href: https://bsky.app/profile/jacobkmcpherson.bsky.social
        aria-label: BlueSky
      - icon: twitter
        href: https://x.com/JacobKMcPherson/
        aria-label: Twitter
      - icon: facebook
        href: https://facebook.com/jacobkmcpherson/
        aria-label: Facebook
      - icon: instagram
        href: https://instagram.com/jkmcpherson_25/
        aria-label: Instagram
      - icon: threads
        href: https://www.threads.com/@jkmcpherson_25
        aria-label: Threads
      - icon: youtube
        href: https://youtube.com/@jacobkmcpherson
        aria-label: YouTube
      - icon: spotify
        href: https://open.spotify.com/user/1241595878
        aria-label: Spotify
      - icon: medium
        href: https://jacobkmcpherson.medium.com/
        aria-label: Medium
      - icon: substack
        href: https://jacobkmcpherson.substack.com/
        aria-label: Substack

  page-footer:
    center: "Copyright © 2025 Jacob K. McPherson - All Rights Reserved"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
