project:
  type: website
  output-dir: docs

website:
  title: "Jacob K. McPherson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog/index.qmd
        text: Blog
      - href: research.qmd
        text: Research
      - href: talks.qmd
        text: Talks
      - href: podcasts.qmd
        text: Podcasts
      - href: gallery.qmd
        text: Gallery
    right:
      - icon: twitter
        href: https://x.com/JacobKMcPherson
        aria-label: Twitter
      - icon: linkedin
        href: https://linkedin.com/in/jacobkmcpherson/
        aria-label: LinkedIn
      - icon: github
        href: https://github.com/JacobKMcPherson
        aria-label: GitHub
      - icon: facebook
        href: https://facebook.com/jacobkmcpherson/
        aria-label: Facebook
      - icon: instagram
        href: https://instagram.com/jkmcpherson_25
        aria-label: Instagram
      - icon: youtube
        href: https://youtube.com/@jacobkmcpherson
        aria-label: YouTube
      #- icon: medium
      #  href: https://medium.com/@yourprofile
      #  aria-label: Medium
      - icon: book
        href: https://scholar.google.com/citations?user=MsZPCoIAAAAJ&hl=en
        aria-label: Google Scholar
      - icon: globe
        href: https://jacobkmcpherson.com
        aria-label: Website
      - icon: calendar
        href: https://jacobkmcpherson.com/calendar
        aria-label: Calendar
      - icon: envelope
        href: mailto:jacobmcpherson@utexas.edu
        aria-label: Email

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



