project:
  type: website
  output-dir: docs

website:
  title: "Jacob K. McPherson"
  navbar:
    left: 
      - href: index.qmd
      - href: about.qmd
      - href: blog/index.qmd
      - href: research.qmd
      - href: talks.qmd
      - href: podcasts.qmd
      - href: gallery.qmd

    right:
      - icon: book-fill
        href: https://author.link/JacobKMcPherson
        text: ""
        aria-label: Author.Link
      - icon: calendar-fill
        href: https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ2xTLcE5R7MwYTlOhowUpeMjXN7cgT8h20PMXwGogkXIen9EUUabmsIjUjQS_eUPq5LWORiUZ0s
        text: ""
        aria-label: Calendar
      - icon: envelope-fill
        href: mailto:jacobmcpherson@utexas.edu
        text: ""
        aria-label: Email
      - icon: globe
        href: https://jacobkmcpherson.com
        text: ""
        aria-label: Website
      - icon: linkedin
        href: https://linkedin.com/in/jacobkmcpherson/
        text: ""
        aria-label: LinkedIn
      - icon: github
        href: https://github.com/JacobKMcPherson
        text: ""
        aria-label: GitHub
      - icon: bluesky
        href: https://bsky.app/profile/JacobKMcPherson.bsky.social
        text:  |
          <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Bluesky_Logo.svg/2319px-Bluesky_Logo.svg.png" alt="Bluesky" style="height:1.2em; vertical-align:middle;">
        aria-label: Bluesky
      - icon: twitter
        href: https://x.com/JacobKMcPherson
        text: ""
        aria-label: Twitter
      - icon: facebook
        href: https://facebook.com/jacobkmcpherson/
        text: ""
        aria-label: Facebook
      - icon: instagram-fill
        href: https://instagram.com/jkmcpherson_25
        text: ""
        aria-label: Instagram
      - icon: youtube
        href: https://youtube.com/@jacobkmcpherson
        text: ""
        aria-label: YouTube
      - icon: medium
        href: https://jacobkmcpherson.medium.com/
        text: ""
        aria-label: Medium

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
