project:
  type: website
  output-dir: docs

website:
  title: "Jacob K. McPherson"
  description: "A Personal Website"
  favicon: https://github.com/mcphersongroup/mcphersongroup.github.io/blob/main/favicon.ico
  navbar:
    logo-href: https://github.com/mcphersongroup/mcphersongroup.github.io/blob/main/favicon.svg
    pinned: true
    background: primary
    search: true
    left: 
      - href: index.qmd
        text: ""
      - href: about.qmd
        text: ""
      - href: blog/index.qmd
        text: ""
      - href: research/index.qmd
        text: ""
      - href: gallery/index.qmd
        text: ""

    right:
      - icon: book
        href: https://author.link/JacobKMcPherson/
        aria-label: Author.Link
      - icon: calendar-date
        href: https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ2xTLcE5R7MwYTlOhowUpeMjXN7cgT8h20PMXwGogkXIen9EUUabmsIjUjQS_eUPq5LWORiUZ0s
        aria-label: Calendar
      - icon: envelope
        href: mailto:jacobmcpherson@utexas.edu
        aria-label: Email
      - icon: building
        href: https://jacobkmcpherson.com
        aria-label: Business
      - icon: people
        href: https://mcphersongroup.github.io/
        aria-label: Research Group
      - icon: linkedin
        href: https://linkedin.com/in/jacobkmcpherson/
        aria-label: LinkedIn
      - icon: github
        href: https://github.com/JacobKMcPherson/
        aria-label: GitHub
      #- icon: bluesky
      #  href: https://bsky.app/profile/JacobKMcPherson.bsky.social
      #  text:  |
      #    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Bluesky_Logo.svg/2319px-Bluesky_Logo.svg.png" alt="Bluesky" style="height:1.0em; vertical-align:middle;">
      #  aria-label: Bluesky
      - icon: twitter
        href: https://x.com/JacobKMcPherson/
        aria-label: Twitter
      - icon: facebook
        href: https://facebook.com/jacobkmcpherson/
        aria-label: Facebook
      - icon: instagram
        href: https://instagram.com/jkmcpherson_25/
        aria-label: Instagram
      - icon: threads
        href: https://www.threads.com/@jkmcpherson_25
        aria-label: Threads
      - icon: youtube
        href: https://youtube.com/@jacobkmcpherson
        aria-label: YouTube
      - icon: spotify
        href: https://open.spotify.com/user/1241595878
        aria-label: Spotify
      - icon: medium
        href: https://jacobkmcpherson.medium.com/
        aria-label: Medium
      - icon: substack
        href: https://jacobkmcpherson.substack.com/
        aria-label: Substack

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
