project:
  type: website
  output-dir: docs

icon-dir: icons

website:
  title: "Jacob K. McPherson"
  navbar:
    left:
      - icon: house
        href: index.qmd
      - icon: user
        href: about.qmd
      - icon: pen
        href: blog/index.qmd
      - icon: flask # or microscope
        href: research.qmd
      - icon: microphone
        href: talks.qmd
      - icon: podcast
        href: podcasts.qmd
      - icon: images
        href: gallery.qmd
    right:
      - icon: book
        href: https://author.link/JacobKMcPherson
        aria-label: Author.Link
      - icon: calendar
        href: https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ2xTLcE5R7MwYTlOhowUpeMjXN7cgT8h20PMXwGogkXIen9EUUabmsIjUjQS_eUPq5LWORiUZ0s
        aria-label: Calendar
      - icon: envelope
        href: mailto:jacobmcpherson@utexas.edu
        aria-label: Email
      - icon: globe
        href: https://jacobkmcpherson.com
        aria-label: Website
      - icon: linkedin
        href: https://linkedin.com/in/jacobkmcpherson/
        aria-label: LinkedIn
      - icon: github
        href: https://github.com/JacobKMcPherson
        aria-label: GitHub
      - icon: bluesky
        href: https://bsky.app/profile/JacobKMcPherson.bsky.social
        aria-label: Bluesky
      - icon: twitter
        href: https://x.com/JacobKMcPherson
        aria-label: Twitter
      - icon: facebook
        href: https://facebook.com/jacobkmcpherson/
        aria-label: Facebook
      - icon: instagram
        href: https://instagram.com/jkmcpherson_25
        aria-label: Instagram
      - icon: youtube
        href: https://youtube.com/@jacobkmcpherson
        aria-label: YouTube
      #- icon: medium
      #  href: https://medium.com/@yourprofile
      #  aria-label: Medium

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



