---
title: "Blog"

listing:
  - id: jacobkmcpherson
    contents: posts
    sort: "date desc"
    type: default
    categories: true
    sort-ui: false
    filter-ui: true
    fields: [image, title, url_source]
  
  - id: clinicianscientist
    contents: clinicianscientist
    sort: "date desc"
    type: default
    categories: true
    sort-ui: false
    filter-ui: true
    fields: [image, title, url_source]
    
  - id: drugdev
    contents: drugdev
    sort: "date desc"
    type: default
    categories: true
    sort-ui: false
    filter-ui: true
    fields: [image, title, url_source]

  - id: infectiousdiseases
    contents: infectiousdiseases
    sort: "date desc"
    type: default
    categories: true
    sort-ui: false
    filter-ui: true
    fields: [image, title, url_source]

  - id: investmenttheory
    contents: investmenttheory
    sort: "date desc"
    type: default
    categories: true
    sort-ui: false
    filter-ui: true
    fields: [image, title, url_source]

  - id: pharmacological
    contents: pharmacological
    sort: "date desc"
    type: default
    categories: true
    sort-ui: false
    filter-ui: true
    fields: [image, title, url_source]
    
  - id: primaryeducation
    contents: primaryeducation
    sort: "date desc"
    type: default
    categories: true
    sort-ui: false
    filter-ui: true
    fields: [image, title, url_source]
    
  - id: receptortheory
    contents: receptortheory
    sort: "date desc"
    type: default
    categories: true
    sort-ui: false
    filter-ui: true
    fields: [image, title, url_source]
    
  - id: thehealthofnations
    contents: thehealthofnations
    sort: "date desc"
    type: default
    categories: true
    sort-ui: false
    filter-ui: true
    fields: [image, title, url_source]
    
  - id: thepharmacologist
    contents: thepharmacologist
    sort: "date desc"
    type: default
    categories: true
    sort-ui: false
    filter-ui: true
    fields: [image, title, url_source]
  
page-layout: full
title-block-banner: false
css: styles.css
---

Welcome to my blog! Also available at [Medium](https://jacobkmcpherson.medium.com/), [Substack](https://jacobkmcpherson.substack.com/), and my website [blog](https://jacobkmcpherson.com/blog). 


Here are some of my latest posts:

###[**My Personal SubStack**](https://jacobkmcpherson.substack.com/)

::: {.jacobkmcpherson}
:::

###[**Infectious Diseases**](https://infectiousdiseases.substack.com/)

*A blog about infectious diseases, epidemiology, and public health.*

::: {.infectiousdiseases}
:::

[**The Health of Nations**](https://thehealthofnations.substack.com/)

*A blog about global health, health policy, and improving health outcomes worldwide.*

::: {.thehealthofnations}
:::

###[**Primary Education**](https://primaryeducation.substack.com/)

*A blog about improving primary education globally.*

::: {.primaryeducation}
:::

###[**Investment Theory**](https://investmenttheory.substack.com/)

*An amateur take on financial markets, investing, and economics.*

::: {.investmenttheory}
:::

###[**Receptor Theory**](https://receptortheory.substack.com/)

*A blog about pharmacodynamics, drug-receptor interactions, and the principles of receptor theory.*

::: {.receptortheory}
:::

###[**Pharmacological**](https://pharmacological.substack.com/)

*A blog about therapeutic science.*

::: {.pharmacological}
:::

###[**Drug Dev**](https://drugdev.substack.com/)

*A blog about drug development, pharmaceutical research, and the journey from lab to market.*

::: {.drugdev}
:::

###[**The Pharmacologist**](https://thepharmacologist.substack.com/)

*A blog about drug mechanisms*

::: {.thepharmacologist}
:::

###[**The Clinician Scientist**](https://clinicianscientist.substack.com/)

*A blog about translational medicine, clinical research, and the intersection of science and patient care.*

::: {.clinicianscientist}
:::